from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# -------- PARSE AI OUTPUT --------
def parse_feedback(feedback):
    missing, improvements, suggestions = [], [], []
    current = None

    for line in feedback.split("\n"):
        line = line.strip()

        if "Missing Skills" in line:
            current = "missing"
        elif "Improvements" in line:
            current = "improvements"
        elif "Suggestions" in line:
            current = "suggestions"
        elif line.startswith("-"):
            if current == "missing":
                missing.append(line)
            elif current == "improvements":
                improvements.append(line)
            elif current == "suggestions":
                suggestions.append(line)

    return missing, improvements, suggestions


# -------- GENERATE PDF --------
def generate_pdf(feedback, username, score, filename="report.pdf"):
    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()

    content = []

    # ---------- TITLE ----------
    content.append(Paragraph("<b>AI Career Report</b>", styles["Title"]))
    content.append(Spacer(1, 10))

    content.append(Paragraph(f"<b>User:</b> {username}", styles["Normal"]))
    content.append(Paragraph(f"<b>Match Score:</b> {score}%", styles["Normal"]))

    content.append(Spacer(1, 15))

    # ---------- PARSE ----------
    missing, improvements, suggestions = parse_feedback(feedback)

    # ---------- MISSING SKILLS ----------
    content.append(Paragraph("<b>Missing Skills</b>", styles["Heading2"]))
    content.append(Spacer(1, 5))

    if missing:
        for item in missing:
            clean = item.lstrip("- ").strip()
            content.append(Paragraph(f"• {clean}", styles["Normal"]))
    else:
        content.append(Paragraph("No major missing skills identified.", styles["Normal"]))

    content.append(Spacer(1, 12))

    # ---------- IMPROVEMENTS ----------
    content.append(Paragraph("<b>Improvements</b>", styles["Heading2"]))
    content.append(Spacer(1, 5))

    if improvements:
        for item in improvements:
            clean = item.lstrip("- ").strip()
            content.append(Paragraph(f"• {clean}", styles["Normal"]))
    else:
        content.append(Paragraph("No major improvements required.", styles["Normal"]))

    content.append(Spacer(1, 12))

    # ---------- SUGGESTIONS ----------
    content.append(Paragraph("<b>Suggestions</b>", styles["Heading2"]))
    content.append(Spacer(1, 5))

    if suggestions:
        for item in suggestions:
            clean = item.lstrip("- ").strip()
            content.append(Paragraph(f"• {clean}", styles["Normal"]))
    else:
        content.append(Paragraph("No suggestions available.", styles["Normal"]))

    content.append(Spacer(1, 20))

    # ---------- FOOTER ----------
    content.append(Paragraph(
        "<i>Generated by AI Career Assistant</i>", styles["Normal"]
    ))

    # ---------- BUILD ----------
    doc.build(content)

    return filename